// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	knapv1alpha1 "github.com/bluebosh/knap/pkg/apis/knap/v1alpha1"
	versioned "github.com/bluebosh/knap/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bluebosh/knap/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/bluebosh/knap/pkg/client/listers/knap/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AppengineInformer provides access to a shared informer and lister for
// Appengines.
type AppengineInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AppengineLister
}

type appengineInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppengineInformer constructs a new informer for Appengine type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppengineInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppengineInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppengineInformer constructs a new informer for Appengine type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppengineInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KnapV1alpha1().Appengines(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KnapV1alpha1().Appengines(namespace).Watch(options)
			},
		},
		&knapv1alpha1.Appengine{},
		resyncPeriod,
		indexers,
	)
}

func (f *appengineInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppengineInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appengineInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&knapv1alpha1.Appengine{}, f.defaultInformer)
}

func (f *appengineInformer) Lister() v1alpha1.AppengineLister {
	return v1alpha1.NewAppengineLister(f.Informer().GetIndexer())
}
