apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: helloworld-pr-
  name: helloworld-pr-1
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: helloworld-git
  params:
    - name: pathToYamlFile
      value: "knative/helloworld.yaml"
    - name: imageUrl
      value: us.icr.io/knative_jordan/picalc
    - name: imageTag
      value: "1.0"
  trigger:
    type: manual
  serviceAccount: pipeline-account
