// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AppengineListerExpansion allows custom methods to be added to
// AppengineLister.
type AppengineListerExpansion interface{}

// AppengineNamespaceListerExpansion allows custom methods to be added to
// AppengineNamespaceLister.
type AppengineNamespaceListerExpansion interface{}
