apiVersion: apps/v1
kind: Deployment
metadata:
  name: knap
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knap
  template:
    metadata:
      labels:
        name: knap
    spec:
      serviceAccountName: knap
      containers:
        - name: knap
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - knap
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knap"
