// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bluebosh/knap/pkg/client/clientset/versioned/typed/knap/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKnapV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKnapV1alpha1) Appengines(namespace string) v1alpha1.AppengineInterface {
	return &FakeAppengines{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKnapV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
